{
    'name': 'One Install All',
    'version': '1.0',
    'category': '',
    'depends': ['OI_support',
                'account_customization',
                'approved_leaves_report',
                'asset_sequence',
                'country_nationality',
                'email_validation',
                'emp_self_services',
                'hr_admin',
                'hr_contract_custom',
                'hr_contract_init',
                'hr_department_sequence',
                'hr_employee_customization',
                'hr_employee_notification',
                'hr_employee_state',
                'hr_job_categories',
                'hr_payslip_addtion',
                'hr_payslip_amendment',
                'hr_policy_group',
                'hr_policy_absence',
                'hr_policy_ot',
                'hr_policy_presence',
                'hr_public_holidays',
                'hr_admin',
                'hr_skill',
                'hr_language',
                'hr_payroll_register',
                'hr_skill',
                'invoice_extension',
                'hr_transfer',
                'payment_voucher_report',
                'purchase_customization',
                'purchase_order_report',
                'purchase_requisition_config',
                'request_management',
                'res_partner_extension',
                'salary_certificate_report',
                'web_m2x_options',
                'white_attached_mimetypes',
                'hr_employee_state',
                'report_invoice',
                'partner_mass_mailing_list',
                'service_management',
                'voucher_workflow_customization',
                'window_action_rule'
                ],
    'author': 'Bista Solutions',
    'description': """
One Install All
    """,
    'website': 'https://www.bistasolutions.com',
    'data': [],
    'test': [],
    'demo': [],
    'installable': True,
    'auto_install': False
}
